title: Regularized Reflections
description: Where AI meets reality
author: Regularized Reflector
url: "https://regularizedreflections.github.io/RegularizedReflections"
baseurl: "/RegularizedReflections"

# Dark theme that actually works
remote_theme: "poole/hyde"  # Sombre et minimaliste

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Collections
collections:
  posts:
    output: true

# Show excerpts
show_excerpts: true
